import { ScoreGauge } from './SellerMedia';
import React, { useState } from 'react';

const box = 'rounded-2xl border border-neutral-200 bg-white p-5 space-y-4';
const btn = 'rounded-xl bg-teal-700 px-4 py-2 text-sm font-bold text-white';
const input = 'w-full rounded-xl border border-neutral-300 bg-white p-3 text-sm';
export const DemoNotice = () => <p className="rounded-xl bg-amber-50 p-3 text-sm text-amber-900">Ambiente demonstrativo. Consultas e formulários desta área usam exemplos e dados desta sessão. Não enviam mensagens nem alteram pedidos reais.</p>;
export function exportRows(name: string, rows: string[][]) {
 const safe = (s: string) => '"' + (/^[=+@-]/.test(s) ? "'" + s : s).replace(/"/g, '""') + '"';
 const url = URL.createObjectURL(new Blob(['\uFEFF' + rows.map(r => r.map(safe).join(';')).join('\r\n')], {type:'text/csv;charset=utf-8'}));
 const a=document.createElement('a'); a.href=url; a.download=name+'.csv'; a.click(); setTimeout(()=>URL.revokeObjectURL(url),1000);
}
export function Consultation({title, folders, rows}: {title:string;folders:string[];rows:string[][];onAction?:unknown}) {
 const [folder,setFolder]=useState(folders[0]); const [query,setQuery]=useState(''); const [selected,setSelected]=useState<string[]|null>(null);
 const [note,setNote]=useState(''); const [saved,setSaved]=useState<Record<string,string>>({});
 const mapped:Record<string,string>={'Postados':'Em trânsito','Entregues':'Entregue','Elegíveis':'Elegível'};
 const filtered=rows.filter(r=>(folder==='Todos'||r[2]===(mapped[folder]||folder))&&r.join(' ').toLowerCase().includes(query.toLowerCase()));
 if(selected) return <section className={box}><button className={btn} onClick={()=>setSelected(null)}>Voltar à consulta</button><h3 className="text-xl font-bold">Relatório de consulta — {selected[0]}</h3><DemoNotice/><dl className="grid gap-4 sm:grid-cols-2">{selected.map((v,i)=><div key={i}><dt className="text-sm text-neutral-500">{['Código','Pedido / produto','Situação','Valor / prazo informado'][i]}</dt><dd className="font-semibold">{v}</dd></div>)}</dl><h4 className="font-bold">Orientação para análise</h4><p>{selected[2]==='Etiqueta pendente'?'Confira endereço, peso e dimensões antes de emitir a etiqueta no serviço de transporte.':selected[2]==='Em trânsito'?'Consulte o rastreamento da transportadora e registre eventuais divergências.':'Confira os dados e registre abaixo as providências necessárias.'}</p><label className="block">Observações<textarea className={input} value={note} onChange={e=>setNote(e.target.value)}/></label><button className={btn} onClick={()=>setSaved({...saved,[selected[0]]:note})}>Guardar análise nesta sessão</button>{saved[selected[0]]!==undefined&&<p role="status">Análise guardada nesta sessão.</p>}<button className={btn} onClick={()=>exportRows('consulta-'+selected[0],[['Código','Referência','Situação','Valor / prazo','Observação','Origem'],[...selected,note,'Demonstração']])}>Baixar relatório CSV</button></section>;
 return <section className={box}><h3 className="text-xl font-bold">{title}</h3><DemoNotice/><div className="flex flex-wrap gap-2">{folders.map(f=><button aria-pressed={folder===f} key={f} className={folder===f?btn:'rounded-xl border p-2 text-sm'} onClick={()=>setFolder(f)}>{f}</button>)}</div><input aria-label="Buscar consulta" className={input} placeholder="Buscar código, pedido ou produto" value={query} onChange={e=>setQuery(e.target.value)}/>{filtered.map(r=><div key={r[0]} className="flex flex-wrap items-center justify-between gap-3 border-b py-3"><div><b>{r[0]}</b><p>{r[1]}</p><p className="text-sm">{r[2]} · {r[3]}</p></div><button className={btn} onClick={()=>{setSelected(r);setNote(saved[r[0]]||'')}}>Consultar</button></div>)}{!filtered.length&&<p>Nenhum registro neste filtro.</p>}<button className={btn} onClick={()=>exportRows('consultas',[['Código','Referência','Situação','Valor / prazo'],...filtered])}>Exportar consulta</button></section>;
}
const knowledge = [
 ['entrega frete prazo envio rastreio transportadora','Como acompanhar o envio?','Confira o código de rastreio e o prazo informado no pedido. Caso não haja atualização, consulte a transportadora antes de prometer uma nova data.','Pós-venda'],
 ['troca devolucao defeito reembolso estorno','Como tratar uma devolução?','Registre o pedido, motivo e evidências. Acompanhe a análise e informe apenas prazos confirmados; um registro nesta tela não autoriza reembolso.','Pós-venda'],
 ['pagamento pix cartao boleto aprovado','Como confirmar pagamento?','Aguarde confirmação do provedor de pagamento. Comprovantes enviados pelo comprador não substituem a confirmação. A integração financeira deste site ainda está pendente.','Vendas'],
 ['estoque quantidade disponivel reposicao','Como responder sobre disponibilidade?','Confira o estoque do produto antes de confirmar disponibilidade. Informe somente a quantidade cadastrada e não prometa reposição sem data confirmada.','Anúncios'],
 ['foto imagem capa anuncio titulo descricao','Como melhorar meu anúncio?','Use fotos nítidas do produto, título com marca e modelo e descrição de medidas, conteúdo e condições. Revise preço e estoque antes de publicar.','Anúncios'],
 ['reputacao score indicador avaliacao nota','Como melhorar a reputação?','Acompanhe atrasos, cancelamentos e reclamações. Resolva problemas e mantenha o estoque atualizado. O score demonstrativo não é uma avaliação real da loja.','Reputação'],
 ['cadastro conta login senha sms biometria','Como verificar meu cadastro?','As validações reais de SMS, biometria e login ainda precisam de integração. Não considere uma aprovação demonstrativa como identidade verificada.','Resumo'],
 ['promocao desconto campanha vitrine marketing','Como planejar uma promoção?','Defina o produto, margem, desconto e datas. Confirme estoque e condições antes da divulgação. O cadastro demonstrativo não ativa campanha externa.','Marketing'],
 ['tamanho medida notebook compatibilidade material chuva impermeavel','O produto é compatível?','Confira medidas, material e compatibilidade na ficha do produto. Se a informação não estiver cadastrada, consulte o fornecedor antes de responder.','Anúncios'],
 ['nota fiscal garantia documento','Como esclarecer garantia e nota fiscal?','Confirme as condições documentadas pelo vendedor e fabricante. Não invente prazo de garantia ou prometa documento que não tenha sido emitido.','Pós-venda'],
 ['cancelamento cancelar pedido','Como analisar um cancelamento?','Confira se o pedido já foi enviado e registre o motivo. Confirme o resultado no sistema de pedidos e pagamentos antes de informar o comprador.','Pós-venda'],
 ['taxa repasse saldo split saque','Como consultar repasses?','Compare valores e taxas com o extrato do provedor. O split e os repasses automáticos ainda não estão conectados neste site.','Vendas']
];
const normalize=(s:string)=>s.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();
export function QuickAnswers({navigate}:{navigate:(tab:string)=>void}) {
 const [query,setQuery]=useState('');const [asked,setAsked]=useState('');const [copied,setCopied]=useState(false);
 const tokens=normalize(asked).split(/\W+/).filter(t=>t.length>3);
 const matches=knowledge.map(k=>({k,score:tokens.filter(t=>k[0].includes(t)).length})).filter(x=>x.score>0).sort((a,b)=>b.score-a.score).slice(0,3);
 return <section className={box}><h3 className="text-xl font-bold">Respostas rápidas do vendedor</h3><p>Digite sua dúvida. As orientações aparecem somente quando você perguntar.</p><form onSubmit={e=>{e.preventDefault();setAsked(query);setCopied(false)}} className="space-y-3"><input required className={input} aria-label="Sua pergunta" placeholder="Ex.: como acompanhar uma devolução?" value={query} onChange={e=>setQuery(e.target.value)}/><button className={btn}>Obter resposta</button></form>{asked&&(!matches.length?<p>Não encontrei uma orientação específica. Informe se a dúvida é sobre produto, pedido, cadastro ou pagamento.</p>:matches.map(({k})=><article key={k[1]} className="rounded-xl bg-teal-50 p-4 space-y-3"><h4 className="font-bold">{k[1]}</h4><p>{k[2]}</p><div className="flex flex-wrap gap-2"><button className={btn} onClick={()=>navigate(k[3])}>Abrir {k[3]}</button><button className={btn} onClick={async()=>{try{await navigator.clipboard.writeText(k[2]);setCopied(true)}catch{setCopied(false)}}}>Copiar orientação</button></div></article>))}{copied&&<p role="status">Orientação copiada.</p>}</section>;
}
type Case={id:string;order:string;type:string;date:string;status:string;description:string;analysis:string};
export function AfterSales({navigate}:{navigate:(tab:string)=>void}) {
 const [tab,setTab]=useState('Reclamações e mediações');const [q,setQ]=useState('');const [date,setDate]=useState('');const [status,setStatus]=useState('Todos');const [sort,setSort]=useState('recent');const [showDate,setShowDate]=useState(false);const [showFilter,setShowFilter]=useState(false);
 const [records,setRecords]=useState<Case[]>([]);const [editing,setEditing]=useState<Case|null>(null);const [showForm,setShowForm]=useState(false);
 const visible=records.filter(r=>r.type===tab&&(!date||r.date>=date)&&(status==='Todos'||r.status===status)&&normalize(r.order+' '+r.description).includes(normalize(q))).sort((a,b)=>sort==='recent'?b.date.localeCompare(a.date):a.date.localeCompare(b.date));
 return <section className={box}><h3 className="text-2xl font-bold">Pós-venda</h3><DemoNotice/><div className="flex flex-wrap gap-2">{['Reclamações e mediações','Mensagens','Devoluções'].map(t=><button className={tab===t?btn:'rounded-xl border p-2'} key={t} onClick={()=>setTab(t)}>{t}</button>)}</div><input className={input} aria-label="Buscar atendimento" value={q} onChange={e=>setQ(e.target.value)} placeholder="Buscar pedido ou assunto"/><div className="flex flex-wrap gap-2"><button className={btn} onClick={()=>setShowDate(!showDate)}>Filtrar por data</button><button className={btn} onClick={()=>setShowFilter(!showFilter)}>Filtrar e ordenar</button><button className={btn} onClick={()=>{setQ('');setDate('');setStatus('Todos');setSort('recent')}}>Limpar busca</button><button className={btn} onClick={()=>navigate('Vendas')}>Consultar pedidos</button><button className={btn} onClick={()=>{setEditing(null);setShowForm(true)}}>Nova análise</button></div>{showDate&&<label>Desde<input className={input} type="date" value={date} onChange={e=>setDate(e.target.value)}/></label>}{showFilter&&<div className="flex gap-3"><select aria-label="Status" className={input} value={status} onChange={e=>setStatus(e.target.value)}>{['Todos','Em análise','Aguardando retorno','Concluído'].map(s=><option key={s}>{s}</option>)}</select><select aria-label="Ordenação" className={input} value={sort} onChange={e=>setSort(e.target.value)}><option value="recent">Mais recentes</option><option value="old">Mais antigos</option></select></div>}
 {showForm&&<form key={editing?.id||'new'} className={box} onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);const r:Case={id:editing?.id||crypto.randomUUID(),order:String(f.get('order')),type:tab,date:String(f.get('date')),status:String(f.get('status')),description:String(f.get('description')),analysis:String(f.get('analysis'))};setRecords(prev=>[...prev.filter(x=>x.id!==r.id),r]);setShowForm(false)}}><h4 className="font-bold">Formulário de análise — {tab}</h4>{[['order','Pedido'],['date','Data'],['description','Assunto'],['analysis','Análise e providências']].map(([name,label])=><label key={name} className="block">{label}<input required name={name} type={name==='date'?'date':'text'} defaultValue={editing?.[name as keyof Case]||''} className={input}/></label>)}<select aria-label="Situação da análise" name="status" defaultValue={editing?.status||'Em análise'} className={input}>{['Em análise','Aguardando retorno','Concluído'].map(s=><option key={s}>{s}</option>)}</select><button className={btn}>Guardar nesta sessão</button><button type="button" className={btn} onClick={()=>setShowForm(false)}>Cancelar</button></form>}
 {visible.map(r=><article className={box} key={r.id}><b>{r.order} · {r.status}</b><p>{r.date} — {r.description}</p><p>{r.analysis}</p><button className={btn} onClick={()=>{setEditing(r);setShowForm(true)}}>Consultar / editar análise</button></article>)}{!visible.length&&<p>Nenhuma análise neste filtro. Use “Nova análise” para preencher um exemplo.</p>}<button className={btn} onClick={()=>exportRows('pos-venda',[['Pedido','Tipo','Data','Situação','Assunto','Análise'],...visible.map(r=>[r.order,r.type,r.date,r.status,r.description,r.analysis])])}>Baixar relatório filtrado</button><QuickAnswers navigate={navigate}/></section>;
}
export function Reputation() {
 const [tab,setTab]=useState('Resumo');const [checks,setChecks]=useState<string[]>([]);const [rating,setRating]=useState('Todas');
 const tasks=['Revisar estoque diariamente','Conferir prazos de postagem','Responder dúvidas com informações confirmadas','Acompanhar reclamações até a solução'];
 return <section className={box}><h3 className="text-2xl font-bold">Reputação e desempenho</h3><ScoreGauge/><p>Sem dados reais de vendas e avaliações conectados. O score ainda não está disponível.</p><div className="flex flex-wrap gap-2">{['Resumo','Indicadores','Avaliações','Como melhorar o score'].map(t=><button key={t} className={tab===t?btn:'rounded-xl border p-3'} onClick={()=>setTab(t)}>{t}</button>)}</div>{tab==='Resumo'?<><h4 className="text-3xl font-bold">Score: —</h4><p>A pontuação exige pedidos e avaliações verificados. Concluir tarefas não altera automaticamente a reputação.</p><div className="grid gap-3 sm:grid-cols-3">{['Indicadores','Avaliações','Como melhorar o score'].map(t=><button className={btn} key={t} onClick={()=>setTab(t)}>{t==='Indicadores'?'Analisar indicadores':t==='Avaliações'?'Ver avaliações':'Ver plano de melhoria'}</button>)}</div></>:tab==='Indicadores'?<><h4 className="font-bold">Indicadores da loja</h4>{[['Reclamações','Pedidos com reclamação / pedidos elegíveis'],['Cancelamentos','Pedidos cancelados pelo vendedor / pedidos elegíveis'],['Envios atrasados','Envios fora do prazo / envios elegíveis']].map(([n,f])=><article key={n} className={box}><b>{n}: —</b><p>{f}</p><small>Sem base de dados para cálculo.</small></article>)}<button className={btn} onClick={()=>exportRows('indicadores',[['Indicador','Resultado'],['Reclamações','Sem dados'],['Cancelamentos','Sem dados'],['Atrasos','Sem dados']])}>Baixar relatório</button></>:tab==='Avaliações'?<><label>Filtrar nota<select className={input} value={rating} onChange={e=>setRating(e.target.value)}>{['Todas','5','4','3','2','1'].map(n=><option key={n}>{n}</option>)}</select></label><p>Nenhuma avaliação verificada disponível{rating!=='Todas'?' com nota '+rating:''}.</p><p>Responda comentários de forma objetiva, reconheça o problema relatado e ofereça os próximos passos confirmados.</p></>:<><h4 className="font-bold">Plano de melhoria</h4><p>{checks.length} de {tasks.length} ações concluídas nesta sessão.</p>{tasks.map(t=><label key={t} className="flex gap-3 border-b py-3"><input type="checkbox" checked={checks.includes(t)} onChange={e=>setChecks(e.target.checked?[...checks,t]:checks.filter(x=>x!==t))}/>{t}</label>)}<button className={btn} onClick={()=>exportRows('plano-melhoria',[['Ação','Andamento'],...tasks.map(t=>[t,checks.includes(t)?'Concluída':'Pendente'])])}>Baixar plano de melhoria</button></>}</section>;
}
