import React, {useState} from 'react';
export type Attachment={name:string;url:string;type:string};
export function MediaUpload({files,setFiles}:{files:Attachment[];setFiles:(f:Attachment[])=>void}) {
 const [error,setError]=useState('');
 return <div className="rounded-xl border p-4 space-y-3"><h4 className="font-bold">Fotos e arquivos do produto</h4><p className="text-sm">Até 8 arquivos JPG, PNG, WEBP ou PDF de até 10 MB. Disponíveis nesta sessão.</p><input aria-label="Selecionar fotos e arquivos" type="file" accept="image/jpeg,image/png,image/webp,application/pdf" multiple onChange={e=>{const chosen=Array.from(e.target.files||[]) as File[];const valid=chosen.filter(f=>f.size<=10485760&&['image/jpeg','image/png','image/webp','application/pdf'].includes(f.type));setError(valid.length!==chosen.length?'Arquivo rejeitado: confira formato e tamanho.':files.length+valid.length>8?'Limite de 8 arquivos.':'');setFiles([...files,...valid.slice(0,8-files.length).map(f=>({name:f.name,type:f.type,url:URL.createObjectURL(f)}))]);e.target.value=''}}/>{error&&<p role="alert">{error}</p>}{files.map((f,i)=><div key={f.url}>{f.type.startsWith('image/')&&<img src={f.url} alt={f.name} className="h-24 object-contain"/>}<a href={f.url} target="_blank" rel="noreferrer" className="text-teal-700 underline">{f.name}</a><button type="button" className="ml-3 underline" onClick={()=>{URL.revokeObjectURL(f.url);setFiles(files.filter((_,n)=>n!==i))}}>Remover</button></div>)}</div>;
}
export function ScoreGauge(){
 return <div className="rounded-2xl bg-teal-50 p-5 space-y-4"><h4 className="font-bold">Pontuação do comerciante</h4><div className="mx-auto flex h-40 w-40 items-center justify-center rounded-full bg-neutral-200"><div className="flex h-32 w-32 flex-col items-center justify-center rounded-full bg-white"><b className="text-4xl">—</b><span>Sem dados</span></div></div><p className="text-sm">Aguardando integração com pedidos e atendimentos verificados. A pontuação não pode ser ajustada manualmente.</p><ul className="space-y-2 text-sm"><li>Pagamentos confirmados: não conectado</li><li>Entregas e cancelamentos: não conectado</li><li>Reclamações e avaliações verificadas: não conectado</li></ul></div>;
}
